project:
  type: website
  output-dir: docs

website:
  title: "Paul-Henri HAUMESSER"
  navbar:
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/phhaumesser   
        target: _blank
      - icon: envelope
        target: mailto:paul.haumesser@cea.fr
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    page-layout: full



